### ISSUE TITLE
Paccmann Model

### ISSUE THREAD

**Issue by 1treu1** [PaccMann/paccmann_proteomics#10]
Good afternoon, I hope you are very well.
I am trying to use one of your models in an investigation, specifically the exp4_longformer.
I want to load this model but I don't know if I'm doing it right. I am loading it this way:

PaccLarge_PATH = '/content/drive/MyDrive/DTI (1)/pretrained_roberta/exp4_longformer'
proTokenizer = RobertaTokenizer.from_pretrained(PaccLarge_PATH) #Fastberta Tokenizer
proEncoder = RobertaModel.from_pretrained(PaccLarge_PATH)  #Fastberta Model

The model is in this folder: https://drive.google.com/drive/folders/1E6j-Zu3TJJsMLEtK2PbzEYr2FQq6xddp?usp=sharing
Is this the correct way to load the model? or is it done in another way? I would appreciate any information

**Comment by drugilsberg** [comment]
Looking at the files what you have there is just the tokenizer. You can find the model with the weights in the Box link present in the README.md

**Comment by 1treu1** [comment]
Sorry, that was not the folder, it is this one: 

https://drive.google.com/drive/folders/1lke2NdGZkpXmTgHmhrzZZbQgcumdwMU7?usp=sharing

Is it correct to load them this way?

PaccLarge_PATH = '/content/drive/MyDrive/DTI (1)/pretrained_roberta/exp4_longformer'
proTokenizer = RobertaTokenizer.from_pretrained(PaccLarge_PATH) #Fastberta Tokenizer
proEncoder = RobertaModel.from_pretrained(PaccLarge_PATH) #Fastberta Model

**Comment by drugilsberg** [comment]
Yep it should be totally fine, the folder you linked contains both the tokenizer and the model weights.

**Comment by drugilsberg** [comment]
@1treu1 actually here you find the recommended way to load the "long" model: https://github.com/PaccMann/paccmann_proteomics/blob/master/scripts/initialize_longformer_from_roberta.py
