### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by nasserhashemi** [PaccMann/paccmann_proteomics#2]
Hi, 
Thanks for your git-hub and congrats for your job;
I have a question; How I can  just call a pretrained model from your work which just use as embedding the sequence; I mean without using any back-propagation; only use pretrained saved parameter model to get the representation of any sequence?  
Thanks so much

**Comment by drugilsberg** [comment]
Hey @nasserhashemi, thanks a lot for the interest.
We don't have an explicit script for doing so, but using the pretrained models we provide for download, you can use the huggingface API to load them and extract the embedding you prefer.
The masked language model prediction script contain an example on how to load the Roberta-based models: https://github.com/PaccMann/paccmann_proteomics/blob/master/scripts/predict_masked_lm.py
That said @mfilipav, can probably be more helpful on this.

**Comment by nasserhashemi** [comment]
Thanks so much for your prompt reply; excellent; will do it

Thanks again

**Comment by drugilsberg** [comment]
Thank you, closing, feel free to reopen.
