### ISSUE TITLE
run_language_modeling_script.sh

### ISSUE THREAD

**Issue by 1treu1** [PaccMann/paccmann_proteomics#5]
Hello, Greetings from Colombia, I like your work with paccmann.

I am running run_language_modeling_script.sh Download the model and databases and modify the paths like this:
![Captura de pantalla de 2021-11-10 14-27-56](https://user-images.githubusercontent.com/71142778/141180218-708d6094-8291-4413-b0b4-97316017a427.png)
I get the following error:
![Captura de pantalla de 2021-11-10 14-25-39](https://user-images.githubusercontent.com/71142778/141179785-9ff104c1-92b7-4b2b-8aa9-a927251e3022.png)

According to what I have read, I think it is because the function that receives the model pytorch_model.bin receives a .json and not a .bin, is this true? or am I loading it wrong, if so how would I load it? or how would the order be?

**Comment by drugilsberg** [comment]
Hi @1treu1 thanks for reporting this. I will look into this as soon as possible. My guess is a version incompatibility in the environment that is setup. Could you report the versions for:
- torch
- paccmann_proteomics
- transformers
- tokenizers

**Comment by 1treu1** [comment]
But, then the routes are well given?

torch = 1.4.0
Paccman proteomics is not installed because pip install -e . does not install it due to the error mentioned in the previous ticket.
transformers = 3.0.2
tokenizers = 0.8.0.rc1

**Comment by drugilsberg** [comment]
@1treu1 have you tried to reinstall after @jannisborn fix: https://github.com/PaccMann/paccmann_proteomics/issues/4?

**Comment by 1treu1** [comment]
Hi @drugilsberg I reinstall the environment, as I was told in the previous case, but I get the following error. does not recognize the following module: 

![Captura de pantalla de 2021-11-11 17-14-03](https://user-images.githubusercontent.com/71142778/141376598-f573870c-0764-4f72-85da-0a19bf7194a0.png)

Another question, if I am giving the model paths right? or should I just give you the folder? 

![Captura de pantalla de 2021-11-10 14-27-56](https://user-images.githubusercontent.com/71142778/141377038-3344633d-9839-497f-817a-2d1cdafb639b.png)

**Comment by jannisborn** [comment]
This is a sign that you did not install the package correctly. Did you see any warnings/errors in the installation? If not, I would redo it, watch closely the logs and check whether you can import the package. I just double-checked the installations locally and for me they work fine (mac os)

**Comment by 1treu1** [comment]
When I did the installation, there was no error, I will do it again from scratch (linux).

**Comment by 1treu1** [comment]
I did it again, and it installs perfectly. But it is not able to read the pytorch_model.bin model.

The error is the next:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

![Captura de pantalla de 2021-11-11 18-01-12](https://user-images.githubusercontent.com/71142778/141381403-a5b7799d-c43e-4fd5-bc29-bd3bbf934998.png)

**Comment by drugilsberg** [comment]
Sorry @1treu1 I completely missed this latest message. Can you paste the exact commands and arguments you are passing to the command? I can't reproduce this error unfortunately

**Comment by drugilsberg** [comment]
Sorry @1treu1 I completely missed this latest message. Can you paste the exact commands and arguments you are passing to the command? I can't reproduce this error unfortunately/
