### ISSUE TITLE
sequence level finetuning task

### ISSUE THREAD

**Issue by 1treu1** [PaccMann/paccmann_proteomics#9]
Good evening, I want to start the bash run_seq_clf_script.sh sequence level setting task. 
I set up the code like this:
![image](https://user-images.githubusercontent.com/71142778/152616787-f302006b-82b8-4d98-ab91-bc5f66b0c7f8.png)
But when I run it, I get the following error:

Traceback (most recent call last):
  File "../paccmann_proteomics/run_sequence_classification.py", line 316, in <module>
    main()
  File "../paccmann_proteomics/run_sequence_classification.py", line 120, in main
    model_args, data_args, training_args = parser.parse_args_into_dataclasses()
  File "/home/sirius/anaconda3/envs/paccmann_proteomics/lib/python3.7/site-packages/transformers/hf_argparser.py", line 144, in parse_args_into_dataclasses
    raise ValueError(f"Some specified arguments are not used by the HfArgumentParser: {remaining_args}")
ValueError: Some specified arguments are not used by the HfArgumentParser: [' ']
run_seq_clf_script.sh: línea 26: --do_eval: order not found

I don't understand the reason for the error, do you happen to know what it is due to?

**Comment by 1treu1** [comment]
Good afternoon, I was able to solve the problem.
The error was that it was not loading the model as I was giving the path to the model folder, but the program only accepts it if it says checkpoint:
* So I took checkpoint-155136 from exp1_roberta_1seq and it worked, the trick is to have the model folder named checkpoint.
* Then it asked me for a file called cached_train_RobertaTokenizer_512_pairwise-string.lock but I couldn't find it in the repo. So I went to the following folder: https://github.com/PaccMann/paccmann_proteomics/tree/master/paccmann_proteomics/data/datasets
And I ran all three scripts and each one gave me a .lock file and I used one of those to solve the problem.
* After that it worked fine, I ran it for 10 epochs but after it finished running it threw some files that I don't know what they mean.
* The files are as follows:
https://drive.google.com/drive/folders/1rR_M2Os3BBSTdwjW3tE0P9GI7Aq4IrV3?usp=sharing
https://drive.google.com/drive/folders/1-K2cjXUTIDLxA-siPwItxMZtu4cN3upo?usp=sharing

I don't know much about this kind of files, do you happen to know how to read them? or what they mean, I was expecting some graph, or the error or the ROC, although I may have done it wrong hehehe, I would appreciate any information.

Greetings

**Comment by drugilsberg** [comment]
Hey @1treu1 those are tensorboard event files. Simply run tensorboard and you should be able to inspect them in the browser (tensorboard instructions here: https://www.tensorflow.org/tensorboard/get_started#:~:text=TensorBoard%20is%20a%20tool%20for,dimensional%20space%2C%20and%20much%20more.).

Regarding ROC and in general metrics computation you can simply load the checkpoint you trained and compute then using a dedicated library such as scikit-learn.

**Comment by 1treu1** [comment]
Thank you!!
I will review it
